### ISSUE TITLE
"Enable auto focus to search box" with "Hide when closed" doesn't work

### ISSUE THREAD

**Issue by FicoPrieto** [processhacker/processhacker#663]
# System Info
```yaml
ProcessHacker: 3.0.3263   x64
Windows:       10.0.19041 x64
```

# Settings
```yaml
Options: 

  General: 
    Hide when closed:                           true
    Process Hacker is the default Task Manager: true
    
  ToolStatus: 
    Enable auto focus to search box: true
```

# Working
- start a new instance of PH via `Ctrl + Shift + Escape`  
  (*search box is focused*)
- execute `Menu > Hacker > Exit`
- start a new instance of PH via `Ctrl + Shift + Escape`  
  (*search box is focused*)

# Not Working
- start a new instance of PH via `Ctrl + Shift + Escape`  
  (*search box is focused*)
- click the `✖` button the title bar to hide PH
- open the existing instance of PH via `Ctrl + Shift + Escape`  
  (*search box is **not** focused*)

# Notes

As shown in the GIF below, the search query is persisted when reopening an existing instance of PH. I'm not sure if that is the case when the auto-focus feature is functional, but it's definitely a nice feature to have. Ideally, the previous query would be pre-selected on auto-focus so that it can be quickly overwritten if needed.

&nbsp;  
![ProcessHacker](https://user-images.githubusercontent.com/22942079/90792941-1bc69080-e2d9-11ea-8ce1-9b62458d2640.gif)
